proxy:
  image: jwilder/nginx-proxy:0.2.0
  restart: always
  ports:
    - "80:80"
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock:ro"

app:
  image: ssunkari/express-soa
  restart: always
  ports:
    - "3000"
  environment:
    - VIRTUAL_HOST=localdocs.net,localhost
    - VIRTUAL_PORT=3000

service_a:
  extends:
    service: app

service_b:
  extends:
    service: app
