/**
 * plugin.js
 *
 * Released under LGPL License.
 * Copyright (c) 1999-2015 Ephox Corp. All rights reserved
 *
 * License: http://www.tinymce.com/license
 * Contributing: http://www.tinymce.com/contributing
 */

/*global tinymce:true */

tinymce.PluginManager.add('iconsocial', function(editor) {
	var icon = [
		['<a href="#" class="soc-twitter"></a>', 'twitter'],
		['<a href="#" class="soc-facebook"></a>', 'facebook'],
		['<a href="#" class="soc-google"></a>', 'google'],
		['<a href="#" class="soc-pinterest"></a>', 'pinterest'],
		['<a href="#" class="soc-foursquare"></a>', 'foursquare'],
		['<a href="#" class="soc-yahoo"></a>', 'yahoo'],
		['<a href="#" class="soc-skype"></a>', 'skype'],
		['<a href="#" class="soc-yelp"></a>', 'yelp'],
		['<a href="#" class="soc-feedburner"></a>', 'feedburner'],
		['<a href="#" class="soc-linkedin"></a>', 'linkedin'],
		['<a href="#" class="soc-viadeo"></a>', 'viadeo'],
		['<a href="#" class="soc-xing"></a>', 'xing'],
		['<a href="#" class="soc-myspace"></a>', 'myspace'],
		['<a href="#" class="soc-soundcloud"></a>', 'soundcloud'],
		['<a href="#" class="soc-spotify"></a>', 'spotify'],
		['<a href="#" class="soc-grooveshark"></a>', 'grooveshark'],
		['<a href="#" class="soc-lastfm"></a>', 'lastfm'],
		['<a href="#" class="soc-youtube"></a>', 'youtube'],
		['<a href="#" class="soc-vimeo"></a>', 'vimeo'],
		['<a href="#" class="soc-dailymotion"></a>', 'dailymotion'],
		['<a href="#" class="soc-vine"></a>', 'vine'],
		['<a href="#" class="soc-flickr"></a>', 'flickr'],
		['<a href="#" class="soc-500px"></a>', '500px'],
		['<a href="#" class="soc-instagram"></a>', 'instagram'],
		['<a href="#" class="soc-wordpress"></a>', 'wordpress'],
		['<a href="#" class="soc-tumblr"></a>', 'tumblr'],
		['<a href="#" class="soc-blogger"></a>', 'blogger'],
		['<a href="#" class="soc-technorati"></a>', 'technorati'],
		['<a href="#" class="soc-reddit"></a>', 'reddit'],
		['<a href="#" class="soc-dribbble"></a>', 'dribbble'],
		['<a href="#" class="soc-stumbleupon"></a>', 'stumbleupon'],
		['<a href="#" class="soc-digg"></a>', 'digg'],
		['<a href="#" class="soc-envato"></a>', 'envato'],
		['<a href="#" class="soc-behance"></a>', 'behance'],
		['<a href="#" class="soc-delicious"></a>', 'delicious'],
		['<a href="#" class="soc-deviantart"></a>', 'deviantart'],
		['<a href="#" class="soc-forrst"></a>', 'forrst'],
		['<a href="#" class="soc-play"></a>', 'play'],
		['<a href="#" class="soc-zerply"></a>', 'zerply'],
		['<a href="#" class="soc-wikipedia"></a>', 'wikipedia'],
		['<a href="#" class="soc-apple"></a>', 'apple'],
		['<a href="#" class="soc-flattr"></a>', 'flattr'],
		['<a href="#" class="soc-github"></a>', 'github'],
		['<a href="#" class="soc-chimein"></a>', 'chimein'],
		['<a href="#" class="soc-friendfeed"></a>', 'friendfeed'],
		['<a href="#" class="soc-newsvine"></a>', 'newsvine'],
		['<a href="#" class="soc-identica"></a>', 'identica'],
		['<a href="#" class="soc-bebo"></a>', 'bebo'],
		['<a href="#" class="soc-zynga"></a>', 'zynga'],
		['<a href="#" class="soc-steam"></a>', 'steam'],
		['<a href="#" class="soc-xbox"></a>', 'xbox'],
		['<a href="#" class="soc-windows"></a>', 'windows'],
		['<a href="#" class="soc-outlook"></a>', 'outlook'],
		['<a href="#" class="soc-coderwall"></a>', 'coderwall'],
		['<a href="#" class="soc-tripadvisor"></a>', 'tripadvisor'],
		['<a href="#" class="soc-appnet"></a>', 'appnet'],
		['<a href="#" class="soc-goodreads"></a>', 'goodreads'],
		['<a href="#" class="soc-tripit"></a>', 'tripit'],
		['<a href="#" class="soc-lanyrd"></a>', 'lanyrd'],
		['<a href="#" class="soc-slideshare"></a>', 'slideshare'],
		['<a href="#" class="soc-buffer"></a>', 'buffer'],
		['<a href="#" class="soc-rss"></a>', 'rss'],
		['<a href="#" class="soc-vkontakte"></a>', 'vkontakte'],
		['<a href="#" class="soc-disqus"></a>', 'disqus'],
		['<a href="#" class="soc-houzz"></a>', 'houzz'],
		['<a href="#" class="soc-mail"></a>', 'mail'],
		['<a href="#" class="soc-patreon"></a>', 'patreon'],
		['<a href="#" class="soc-paypal"></a>', 'paypal'],
		['<a href="#" class="soc-playstation"></a>', 'playstation'],
		['<a href="#" class="soc-smugmug"></a>', 'smugmug'],
		['<a href="#" class="soc-swarm"></a>', 'swarm'],
		['<a href="#" class="soc-triplej"></a>', 'triplej'],
		['<a href="#" class="soc-yammer"></a>', 'yammer'],
		['<a href="#" class="soc-stackoverflow"></a>', 'stackoverflow'],
		['<a href="#" class="soc-drupal"></a>', 'drupal'],
		['<a href="#" class="soc-odnoklassniki"></a>', 'odnoklassniki'],
		['<a href="#" class="soc-android"></a>', 'android'],
		['<a href="#" class="soc-meetup"></a>', 'meetup'],
		['<a href="#" class="soc-persona"></a>', 'persona'],
		['<a href="#" class="soc-amazon"></a>', 'amazon'],
		['<a href="#" class="soc-ello"></a>', 'ello'],
		['<a href="#" class="soc-mixcloud"></a>', 'mixcloud'],
		['<a href="#" class="soc-8tracks"></a>', '8tracks'],
		['<a href="#" class="soc-twitch"></a>', 'twitch'],
		['<a href="#" class="soc-airbnb"></a>', 'airbnb'],
		['<a href="#" class="soc-pocket"></a>', 'pocket'],
		['<a href="#" class="border-icon soc-twitter"></a>', 'twitter'],
		['<a href="#" class="border-icon soc-facebook"></a>', 'facebook'],
		['<a href="#" class="border-icon soc-google"></a>', 'google'],
		['<a href="#" class="border-icon soc-pinterest"></a>', 'pinterest'],
		['<a href="#" class="border-icon soc-foursquare"></a>', 'foursquare'],
		['<a href="#" class="border-icon soc-yahoo"></a>', 'yahoo'],
		['<a href="#" class="border-icon soc-skype"></a>', 'skype'],
		['<a href="#" class="border-icon soc-yelp"></a>', 'yelp'],
		['<a href="#" class="border-icon soc-feedburner"></a>', 'feedburner'],
		['<a href="#" class="border-icon soc-linkedin"></a>', 'linkedin'],
		['<a href="#" class="border-icon soc-viadeo"></a>', 'viadeo'],
		['<a href="#" class="border-icon soc-xing"></a>', 'xing'],
		['<a href="#" class="border-icon soc-myspace"></a>', 'myspace'],
		['<a href="#" class="border-icon soc-soundcloud"></a>', 'soundcloud'],
		['<a href="#" class="border-icon soc-spotify"></a>', 'spotify'],
		['<a href="#" class="border-icon soc-grooveshark"></a>', 'grooveshark'],
		['<a href="#" class="border-icon soc-lastfm"></a>', 'lastfm'],
		['<a href="#" class="border-icon soc-youtube"></a>', 'youtube'],
		['<a href="#" class="border-icon soc-vimeo"></a>', 'vimeo'],
		['<a href="#" class="border-icon soc-dailymotion"></a>', 'dailymotion'],
		['<a href="#" class="border-icon soc-vine"></a>', 'vine'],
		['<a href="#" class="border-icon soc-flickr"></a>', 'flickr'],
		['<a href="#" class="border-icon soc-500px"></a>', '500px'],
		['<a href="#" class="border-icon soc-instagram"></a>', 'instagram'],
		['<a href="#" class="border-icon soc-wordpress"></a>', 'wordpress'],
		['<a href="#" class="border-icon soc-tumblr"></a>', 'tumblr'],
		['<a href="#" class="border-icon soc-blogger"></a>', 'blogger'],
		['<a href="#" class="border-icon soc-technorati"></a>', 'technorati'],
		['<a href="#" class="border-icon soc-reddit"></a>', 'reddit'],
		['<a href="#" class="border-icon soc-dribbble"></a>', 'dribbble'],
		['<a href="#" class="border-icon soc-stumbleupon"></a>', 'stumbleupon'],
		['<a href="#" class="border-icon soc-digg"></a>', 'digg'],
		['<a href="#" class="border-icon soc-envato"></a>', 'envato'],
		['<a href="#" class="border-icon soc-behance"></a>', 'behance'],
		['<a href="#" class="border-icon soc-delicious"></a>', 'delicious'],
		['<a href="#" class="border-icon soc-deviantart"></a>', 'deviantart'],
		['<a href="#" class="border-icon soc-forrst"></a>', 'forrst'],
		['<a href="#" class="border-icon soc-play"></a>', 'play'],
		['<a href="#" class="border-icon soc-zerply"></a>', 'zerply'],
		['<a href="#" class="border-icon soc-wikipedia"></a>', 'wikipedia'],
		['<a href="#" class="border-icon soc-apple"></a>', 'apple'],
		['<a href="#" class="border-icon soc-flattr"></a>', 'flattr'],
		['<a href="#" class="border-icon soc-github"></a>', 'github'],
		['<a href="#" class="border-icon soc-chimein"></a>', 'chimein'],
		['<a href="#" class="border-icon soc-friendfeed"></a>', 'friendfeed'],
		['<a href="#" class="border-icon soc-newsvine"></a>', 'newsvine'],
		['<a href="#" class="border-icon soc-identica"></a>', 'identica'],
		['<a href="#" class="border-icon soc-bebo"></a>', 'bebo'],
		['<a href="#" class="border-icon soc-zynga"></a>', 'zynga'],
		['<a href="#" class="border-icon soc-steam"></a>', 'steam'],
		['<a href="#" class="border-icon soc-xbox"></a>', 'xbox'],
		['<a href="#" class="border-icon soc-windows"></a>', 'windows'],
		['<a href="#" class="border-icon soc-outlook"></a>', 'outlook'],
		['<a href="#" class="border-icon soc-coderwall"></a>', 'coderwall'],
		['<a href="#" class="border-icon soc-tripadvisor"></a>', 'tripadvisor'],
		['<a href="#" class="border-icon soc-appnet"></a>', 'appnet'],
		['<a href="#" class="border-icon soc-goodreads"></a>', 'goodreads'],
		['<a href="#" class="border-icon soc-tripit"></a>', 'tripit'],
		['<a href="#" class="border-icon soc-lanyrd"></a>', 'lanyrd'],
		['<a href="#" class="border-icon soc-slideshare"></a>', 'slideshare'],
		['<a href="#" class="border-icon soc-buffer"></a>', 'buffer'],
		['<a href="#" class="border-icon soc-rss"></a>', 'rss'],
		['<a href="#" class="border-icon soc-vkontakte"></a>', 'vkontakte'],
		['<a href="#" class="border-icon soc-disqus"></a>', 'disqus'],
		['<a href="#" class="border-icon soc-houzz"></a>', 'houzz'],
		['<a href="#" class="border-icon soc-mail"></a>', 'mail'],
		['<a href="#" class="border-icon soc-patreon"></a>', 'patreon'],
		['<a href="#" class="border-icon soc-paypal"></a>', 'paypal'],
		['<a href="#" class="border-icon soc-playstation"></a>', 'playstation'],
		['<a href="#" class="border-icon soc-smugmug"></a>', 'smugmug'],
		['<a href="#" class="border-icon soc-swarm"></a>', 'swarm'],
		['<a href="#" class="border-icon soc-triplej"></a>', 'triplej'],
		['<a href="#" class="border-icon soc-yammer"></a>', 'yammer'],
		['<a href="#" class="border-icon soc-stackoverflow"></a>', 'stackoverflow'],
		['<a href="#" class="border-icon soc-drupal"></a>', 'drupal'],
		['<a href="#" class="border-icon soc-odnoklassniki"></a>', 'odnoklassniki'],
		['<a href="#" class="border-icon soc-android"></a>', 'android'],
		['<a href="#" class="border-icon soc-meetup"></a>', 'meetup'],
		['<a href="#" class="border-icon soc-persona"></a>', 'persona'],
		['<a href="#" class="border-icon soc-amazon"></a>', 'amazon'],
		['<a href="#" class="border-icon soc-ello"></a>', 'ello'],
		['<a href="#" class="border-icon soc-mixcloud"></a>', 'mixcloud'],
		['<a href="#" class="border-icon soc-8tracks"></a>', '8tracks'],
		['<a href="#" class="border-icon soc-twitch"></a>', 'twitch'],
		['<a href="#" class="border-icon soc-airbnb"></a>', 'airbnb'],
		['<a href="#" class="border-icon soc-pocket"></a>', 'pocket'],
		['<a href="#" class="border-icon rounded-icon soc-twitter"></a>', 'twitter'],
		['<a href="#" class="border-icon rounded-icon soc-facebook"></a>', 'facebook'],
		['<a href="#" class="border-icon rounded-icon soc-google"></a>', 'google'],
		['<a href="#" class="border-icon rounded-icon soc-pinterest"></a>', 'pinterest'],
		['<a href="#" class="border-icon rounded-icon soc-foursquare"></a>', 'foursquare'],
		['<a href="#" class="border-icon rounded-icon soc-yahoo"></a>', 'yahoo'],
		['<a href="#" class="border-icon rounded-icon soc-skype"></a>', 'skype'],
		['<a href="#" class="border-icon rounded-icon soc-yelp"></a>', 'yelp'],
		['<a href="#" class="border-icon rounded-icon soc-feedburner"></a>', 'feedburner'],
		['<a href="#" class="border-icon rounded-icon soc-linkedin"></a>', 'linkedin'],
		['<a href="#" class="border-icon rounded-icon soc-viadeo"></a>', 'viadeo'],
		['<a href="#" class="border-icon rounded-icon soc-xing"></a>', 'xing'],
		['<a href="#" class="border-icon rounded-icon soc-myspace"></a>', 'myspace'],
		['<a href="#" class="border-icon rounded-icon soc-soundcloud"></a>', 'soundcloud'],
		['<a href="#" class="border-icon rounded-icon soc-spotify"></a>', 'spotify'],
		['<a href="#" class="border-icon rounded-icon soc-grooveshark"></a>', 'grooveshark'],
		['<a href="#" class="border-icon rounded-icon soc-lastfm"></a>', 'lastfm'],
		['<a href="#" class="border-icon rounded-icon soc-youtube"></a>', 'youtube'],
		['<a href="#" class="border-icon rounded-icon soc-vimeo"></a>', 'vimeo'],
		['<a href="#" class="border-icon rounded-icon soc-dailymotion"></a>', 'dailymotion'],
		['<a href="#" class="border-icon rounded-icon soc-vine"></a>', 'vine'],
		['<a href="#" class="border-icon rounded-icon soc-flickr"></a>', 'flickr'],
		['<a href="#" class="border-icon rounded-icon soc-500px"></a>', '500px'],
		['<a href="#" class="border-icon rounded-icon soc-instagram"></a>', 'instagram'],
		['<a href="#" class="border-icon rounded-icon soc-wordpress"></a>', 'wordpress'],
		['<a href="#" class="border-icon rounded-icon soc-tumblr"></a>', 'tumblr'],
		['<a href="#" class="border-icon rounded-icon soc-blogger"></a>', 'blogger'],
		['<a href="#" class="border-icon rounded-icon soc-technorati"></a>', 'technorati'],
		['<a href="#" class="border-icon rounded-icon soc-reddit"></a>', 'reddit'],
		['<a href="#" class="border-icon rounded-icon soc-dribbble"></a>', 'dribbble'],
		['<a href="#" class="border-icon rounded-icon soc-stumbleupon"></a>', 'stumbleupon'],
		['<a href="#" class="border-icon rounded-icon soc-digg"></a>', 'digg'],
		['<a href="#" class="border-icon rounded-icon soc-envato"></a>', 'envato'],
		['<a href="#" class="border-icon rounded-icon soc-behance"></a>', 'behance'],
		['<a href="#" class="border-icon rounded-icon soc-delicious"></a>', 'delicious'],
		['<a href="#" class="border-icon rounded-icon soc-deviantart"></a>', 'deviantart'],
		['<a href="#" class="border-icon rounded-icon soc-forrst"></a>', 'forrst'],
		['<a href="#" class="border-icon rounded-icon soc-play"></a>', 'play'],
		['<a href="#" class="border-icon rounded-icon soc-zerply"></a>', 'zerply'],
		['<a href="#" class="border-icon rounded-icon soc-wikipedia"></a>', 'wikipedia'],
		['<a href="#" class="border-icon rounded-icon soc-apple"></a>', 'apple'],
		['<a href="#" class="border-icon rounded-icon soc-flattr"></a>', 'flattr'],
		['<a href="#" class="border-icon rounded-icon soc-github"></a>', 'github'],
		['<a href="#" class="border-icon rounded-icon soc-chimein"></a>', 'chimein'],
		['<a href="#" class="border-icon rounded-icon soc-friendfeed"></a>', 'friendfeed'],
		['<a href="#" class="border-icon rounded-icon soc-newsvine"></a>', 'newsvine'],
		['<a href="#" class="border-icon rounded-icon soc-identica"></a>', 'identica'],
		['<a href="#" class="border-icon rounded-icon soc-bebo"></a>', 'bebo'],
		['<a href="#" class="border-icon rounded-icon soc-zynga"></a>', 'zynga'],
		['<a href="#" class="border-icon rounded-icon soc-steam"></a>', 'steam'],
		['<a href="#" class="border-icon rounded-icon soc-xbox"></a>', 'xbox'],
		['<a href="#" class="border-icon rounded-icon soc-windows"></a>', 'windows'],
		['<a href="#" class="border-icon rounded-icon soc-outlook"></a>', 'outlook'],
		['<a href="#" class="border-icon rounded-icon soc-coderwall"></a>', 'coderwall'],
		['<a href="#" class="border-icon rounded-icon soc-tripadvisor"></a>', 'tripadvisor'],
		['<a href="#" class="border-icon rounded-icon soc-appnet"></a>', 'appnet'],
		['<a href="#" class="border-icon rounded-icon soc-goodreads"></a>', 'goodreads'],
		['<a href="#" class="border-icon rounded-icon soc-tripit"></a>', 'tripit'],
		['<a href="#" class="border-icon rounded-icon soc-lanyrd"></a>', 'lanyrd'],
		['<a href="#" class="border-icon rounded-icon soc-slideshare"></a>', 'slideshare'],
		['<a href="#" class="border-icon rounded-icon soc-buffer"></a>', 'buffer'],
		['<a href="#" class="border-icon rounded-icon soc-rss"></a>', 'rss'],
		['<a href="#" class="border-icon rounded-icon soc-vkontakte"></a>', 'vkontakte'],
		['<a href="#" class="border-icon rounded-icon soc-disqus"></a>', 'disqus'],
		['<a href="#" class="border-icon rounded-icon soc-houzz"></a>', 'houzz'],
		['<a href="#" class="border-icon rounded-icon soc-mail"></a>', 'mail'],
		['<a href="#" class="border-icon rounded-icon soc-patreon"></a>', 'patreon'],
		['<a href="#" class="border-icon rounded-icon soc-paypal"></a>', 'paypal'],
		['<a href="#" class="border-icon rounded-icon soc-playstation"></a>', 'playstation'],
		['<a href="#" class="border-icon rounded-icon soc-smugmug"></a>', 'smugmug'],
		['<a href="#" class="border-icon rounded-icon soc-swarm"></a>', 'swarm'],
		['<a href="#" class="border-icon rounded-icon soc-triplej"></a>', 'triplej'],
		['<a href="#" class="border-icon rounded-icon soc-yammer"></a>', 'yammer'],
		['<a href="#" class="border-icon rounded-icon soc-stackoverflow"></a>', 'stackoverflow'],
		['<a href="#" class="border-icon rounded-icon soc-drupal"></a>', 'drupal'],
		['<a href="#" class="border-icon rounded-icon soc-odnoklassniki"></a>', 'odnoklassniki'],
		['<a href="#" class="border-icon rounded-icon soc-android"></a>', 'android'],
		['<a href="#" class="border-icon rounded-icon soc-meetup"></a>', 'meetup'],
		['<a href="#" class="border-icon rounded-icon soc-persona"></a>', 'persona'],
		['<a href="#" class="border-icon rounded-icon soc-amazon"></a>', 'amazon'],
		['<a href="#" class="border-icon rounded-icon soc-ello"></a>', 'ello'],
		['<a href="#" class="border-icon rounded-icon soc-mixcloud"></a>', 'mixcloud'],
		['<a href="#" class="border-icon rounded-icon soc-8tracks"></a>', '8tracks'],
		['<a href="#" class="border-icon rounded-icon soc-twitch"></a>', 'twitch'],
		['<a href="#" class="border-icon rounded-icon soc-airbnb"></a>', 'airbnb'],
		['<a href="#" class="border-icon rounded-icon soc-pocket"></a>', 'pocket'],
		['<a href="#" class="bg-icon soc-twitter"></a>', 'twitter'],
		['<a href="#" class="bg-icon soc-facebook"></a>', 'facebook'],
		['<a href="#" class="bg-icon soc-google"></a>', 'google'],
		['<a href="#" class="bg-icon soc-pinterest"></a>', 'pinterest'],
		['<a href="#" class="bg-icon soc-foursquare"></a>', 'foursquare'],
		['<a href="#" class="bg-icon soc-yahoo"></a>', 'yahoo'],
		['<a href="#" class="bg-icon soc-skype"></a>', 'skype'],
		['<a href="#" class="bg-icon soc-yelp"></a>', 'yelp'],
		['<a href="#" class="bg-icon soc-feedburner"></a>', 'feedburner'],
		['<a href="#" class="bg-icon soc-linkedin"></a>', 'linkedin'],
		['<a href="#" class="bg-icon soc-viadeo"></a>', 'viadeo'],
		['<a href="#" class="bg-icon soc-xing"></a>', 'xing'],
		['<a href="#" class="bg-icon soc-myspace"></a>', 'myspace'],
		['<a href="#" class="bg-icon soc-soundcloud"></a>', 'soundcloud'],
		['<a href="#" class="bg-icon soc-spotify"></a>', 'spotify'],
		['<a href="#" class="bg-icon soc-grooveshark"></a>', 'grooveshark'],
		['<a href="#" class="bg-icon soc-lastfm"></a>', 'lastfm'],
		['<a href="#" class="bg-icon soc-youtube"></a>', 'youtube'],
		['<a href="#" class="bg-icon soc-vimeo"></a>', 'vimeo'],
		['<a href="#" class="bg-icon soc-dailymotion"></a>', 'dailymotion'],
		['<a href="#" class="bg-icon soc-vine"></a>', 'vine'],
		['<a href="#" class="bg-icon soc-flickr"></a>', 'flickr'],
		['<a href="#" class="bg-icon soc-500px"></a>', '500px'],
		['<a href="#" class="bg-icon soc-instagram"></a>', 'instagram'],
		['<a href="#" class="bg-icon soc-wordpress"></a>', 'wordpress'],
		['<a href="#" class="bg-icon soc-tumblr"></a>', 'tumblr'],
		['<a href="#" class="bg-icon soc-blogger"></a>', 'blogger'],
		['<a href="#" class="bg-icon soc-technorati"></a>', 'technorati'],
		['<a href="#" class="bg-icon soc-reddit"></a>', 'reddit'],
		['<a href="#" class="bg-icon soc-dribbble"></a>', 'dribbble'],
		['<a href="#" class="bg-icon soc-stumbleupon"></a>', 'stumbleupon'],
		['<a href="#" class="bg-icon soc-digg"></a>', 'digg'],
		['<a href="#" class="bg-icon soc-envato"></a>', 'envato'],
		['<a href="#" class="bg-icon soc-behance"></a>', 'behance'],
		['<a href="#" class="bg-icon soc-delicious"></a>', 'delicious'],
		['<a href="#" class="bg-icon soc-deviantart"></a>', 'deviantart'],
		['<a href="#" class="bg-icon soc-forrst"></a>', 'forrst'],
		['<a href="#" class="bg-icon soc-play"></a>', 'play'],
		['<a href="#" class="bg-icon soc-zerply"></a>', 'zerply'],
		['<a href="#" class="bg-icon soc-wikipedia"></a>', 'wikipedia'],
		['<a href="#" class="bg-icon soc-apple"></a>', 'apple'],
		['<a href="#" class="bg-icon soc-flattr"></a>', 'flattr'],
		['<a href="#" class="bg-icon soc-github"></a>', 'github'],
		['<a href="#" class="bg-icon soc-chimein"></a>', 'chimein'],
		['<a href="#" class="bg-icon soc-friendfeed"></a>', 'friendfeed'],
		['<a href="#" class="bg-icon soc-newsvine"></a>', 'newsvine'],
		['<a href="#" class="bg-icon soc-identica"></a>', 'identica'],
		['<a href="#" class="bg-icon soc-bebo"></a>', 'bebo'],
		['<a href="#" class="bg-icon soc-zynga"></a>', 'zynga'],
		['<a href="#" class="bg-icon soc-steam"></a>', 'steam'],
		['<a href="#" class="bg-icon soc-xbox"></a>', 'xbox'],
		['<a href="#" class="bg-icon soc-windows"></a>', 'windows'],
		['<a href="#" class="bg-icon soc-outlook"></a>', 'outlook'],
		['<a href="#" class="bg-icon soc-coderwall"></a>', 'coderwall'],
		['<a href="#" class="bg-icon soc-tripadvisor"></a>', 'tripadvisor'],
		['<a href="#" class="bg-icon soc-appnet"></a>', 'appnet'],
		['<a href="#" class="bg-icon soc-goodreads"></a>', 'goodreads'],
		['<a href="#" class="bg-icon soc-tripit"></a>', 'tripit'],
		['<a href="#" class="bg-icon soc-lanyrd"></a>', 'lanyrd'],
		['<a href="#" class="bg-icon soc-slideshare"></a>', 'slideshare'],
		['<a href="#" class="bg-icon soc-buffer"></a>', 'buffer'],
		['<a href="#" class="bg-icon soc-rss"></a>', 'rss'],
		['<a href="#" class="bg-icon soc-vkontakte"></a>', 'vkontakte'],
		['<a href="#" class="bg-icon soc-disqus"></a>', 'disqus'],
		['<a href="#" class="bg-icon soc-houzz"></a>', 'houzz'],
		['<a href="#" class="bg-icon soc-mail"></a>', 'mail'],
		['<a href="#" class="bg-icon soc-patreon"></a>', 'patreon'],
		['<a href="#" class="bg-icon soc-paypal"></a>', 'paypal'],
		['<a href="#" class="bg-icon soc-playstation"></a>', 'playstation'],
		['<a href="#" class="bg-icon soc-smugmug"></a>', 'smugmug'],
		['<a href="#" class="bg-icon soc-swarm"></a>', 'swarm'],
		['<a href="#" class="bg-icon soc-triplej"></a>', 'triplej'],
		['<a href="#" class="bg-icon soc-yammer"></a>', 'yammer'],
		['<a href="#" class="bg-icon soc-stackoverflow"></a>', 'stackoverflow'],
		['<a href="#" class="bg-icon soc-drupal"></a>', 'drupal'],
		['<a href="#" class="bg-icon soc-odnoklassniki"></a>', 'odnoklassniki'],
		['<a href="#" class="bg-icon soc-android"></a>', 'android'],
		['<a href="#" class="bg-icon soc-meetup"></a>', 'meetup'],
		['<a href="#" class="bg-icon soc-persona"></a>', 'persona'],
		['<a href="#" class="bg-icon soc-amazon"></a>', 'amazon'],
		['<a href="#" class="bg-icon soc-ello"></a>', 'ello'],
		['<a href="#" class="bg-icon soc-mixcloud"></a>', 'mixcloud'],
		['<a href="#" class="bg-icon soc-8tracks"></a>', '8tracks'],
		['<a href="#" class="bg-icon soc-twitch"></a>', 'twitch'],
		['<a href="#" class="bg-icon soc-airbnb"></a>', 'airbnb'],
		['<a href="#" class="bg-icon soc-pocket"></a>', 'pocket'],
		['<a href="#" class="bg-icon rounded-icon soc-twitter"></a>', 'twitter'],
		['<a href="#" class="bg-icon rounded-icon soc-facebook"></a>', 'facebook'],
		['<a href="#" class="bg-icon rounded-icon soc-google"></a>', 'google'],
		['<a href="#" class="bg-icon rounded-icon soc-pinterest"></a>', 'pinterest'],
		['<a href="#" class="bg-icon rounded-icon soc-foursquare"></a>', 'foursquare'],
		['<a href="#" class="bg-icon rounded-icon soc-yahoo"></a>', 'yahoo'],
		['<a href="#" class="bg-icon rounded-icon soc-skype"></a>', 'skype'],
		['<a href="#" class="bg-icon rounded-icon soc-yelp"></a>', 'yelp'],
		['<a href="#" class="bg-icon rounded-icon soc-feedburner"></a>', 'feedburner'],
		['<a href="#" class="bg-icon rounded-icon soc-linkedin"></a>', 'linkedin'],
		['<a href="#" class="bg-icon rounded-icon soc-viadeo"></a>', 'viadeo'],
		['<a href="#" class="bg-icon rounded-icon soc-xing"></a>', 'xing'],
		['<a href="#" class="bg-icon rounded-icon soc-myspace"></a>', 'myspace'],
		['<a href="#" class="bg-icon rounded-icon soc-soundcloud"></a>', 'soundcloud'],
		['<a href="#" class="bg-icon rounded-icon soc-spotify"></a>', 'spotify'],
		['<a href="#" class="bg-icon rounded-icon soc-grooveshark"></a>', 'grooveshark'],
		['<a href="#" class="bg-icon rounded-icon soc-lastfm"></a>', 'lastfm'],
		['<a href="#" class="bg-icon rounded-icon soc-youtube"></a>', 'youtube'],
		['<a href="#" class="bg-icon rounded-icon soc-vimeo"></a>', 'vimeo'],
		['<a href="#" class="bg-icon rounded-icon soc-dailymotion"></a>', 'dailymotion'],
		['<a href="#" class="bg-icon rounded-icon soc-vine"></a>', 'vine'],
		['<a href="#" class="bg-icon rounded-icon soc-flickr"></a>', 'flickr'],
		['<a href="#" class="bg-icon rounded-icon soc-500px"></a>', '500px'],
		['<a href="#" class="bg-icon rounded-icon soc-instagram"></a>', 'instagram'],
		['<a href="#" class="bg-icon rounded-icon soc-wordpress"></a>', 'wordpress'],
		['<a href="#" class="bg-icon rounded-icon soc-tumblr"></a>', 'tumblr'],
		['<a href="#" class="bg-icon rounded-icon soc-blogger"></a>', 'blogger'],
		['<a href="#" class="bg-icon rounded-icon soc-technorati"></a>', 'technorati'],
		['<a href="#" class="bg-icon rounded-icon soc-reddit"></a>', 'reddit'],
		['<a href="#" class="bg-icon rounded-icon soc-dribbble"></a>', 'dribbble'],
		['<a href="#" class="bg-icon rounded-icon soc-stumbleupon"></a>', 'stumbleupon'],
		['<a href="#" class="bg-icon rounded-icon soc-digg"></a>', 'digg'],
		['<a href="#" class="bg-icon rounded-icon soc-envato"></a>', 'envato'],
		['<a href="#" class="bg-icon rounded-icon soc-behance"></a>', 'behance'],
		['<a href="#" class="bg-icon rounded-icon soc-delicious"></a>', 'delicious'],
		['<a href="#" class="bg-icon rounded-icon soc-deviantart"></a>', 'deviantart'],
		['<a href="#" class="bg-icon rounded-icon soc-forrst"></a>', 'forrst'],
		['<a href="#" class="bg-icon rounded-icon soc-play"></a>', 'play'],
		['<a href="#" class="bg-icon rounded-icon soc-zerply"></a>', 'zerply'],
		['<a href="#" class="bg-icon rounded-icon soc-wikipedia"></a>', 'wikipedia'],
		['<a href="#" class="bg-icon rounded-icon soc-apple"></a>', 'apple'],
		['<a href="#" class="bg-icon rounded-icon soc-flattr"></a>', 'flattr'],
		['<a href="#" class="bg-icon rounded-icon soc-github"></a>', 'github'],
		['<a href="#" class="bg-icon rounded-icon soc-chimein"></a>', 'chimein'],
		['<a href="#" class="bg-icon rounded-icon soc-friendfeed"></a>', 'friendfeed'],
		['<a href="#" class="bg-icon rounded-icon soc-newsvine"></a>', 'newsvine'],
		['<a href="#" class="bg-icon rounded-icon soc-identica"></a>', 'identica'],
		['<a href="#" class="bg-icon rounded-icon soc-bebo"></a>', 'bebo'],
		['<a href="#" class="bg-icon rounded-icon soc-zynga"></a>', 'zynga'],
		['<a href="#" class="bg-icon rounded-icon soc-steam"></a>', 'steam'],
		['<a href="#" class="bg-icon rounded-icon soc-xbox"></a>', 'xbox'],
		['<a href="#" class="bg-icon rounded-icon soc-windows"></a>', 'windows'],
		['<a href="#" class="bg-icon rounded-icon soc-outlook"></a>', 'outlook'],
		['<a href="#" class="bg-icon rounded-icon soc-coderwall"></a>', 'coderwall'],
		['<a href="#" class="bg-icon rounded-icon soc-tripadvisor"></a>', 'tripadvisor'],
		['<a href="#" class="bg-icon rounded-icon soc-appnet"></a>', 'appnet'],
		['<a href="#" class="bg-icon rounded-icon soc-goodreads"></a>', 'goodreads'],
		['<a href="#" class="bg-icon rounded-icon soc-tripit"></a>', 'tripit'],
		['<a href="#" class="bg-icon rounded-icon soc-lanyrd"></a>', 'lanyrd'],
		['<a href="#" class="bg-icon rounded-icon soc-slideshare"></a>', 'slideshare'],
		['<a href="#" class="bg-icon rounded-icon soc-buffer"></a>', 'buffer'],
		['<a href="#" class="bg-icon rounded-icon soc-rss"></a>', 'rss'],
		['<a href="#" class="bg-icon rounded-icon soc-vkontakte"></a>', 'vkontakte'],
		['<a href="#" class="bg-icon rounded-icon soc-disqus"></a>', 'disqus'],
		['<a href="#" class="bg-icon rounded-icon soc-houzz"></a>', 'houzz'],
		['<a href="#" class="bg-icon rounded-icon soc-mail"></a>', 'mail'],
		['<a href="#" class="bg-icon rounded-icon soc-patreon"></a>', 'patreon'],
		['<a href="#" class="bg-icon rounded-icon soc-paypal"></a>', 'paypal'],
		['<a href="#" class="bg-icon rounded-icon soc-playstation"></a>', 'playstation'],
		['<a href="#" class="bg-icon rounded-icon soc-smugmug"></a>', 'smugmug'],
		['<a href="#" class="bg-icon rounded-icon soc-swarm"></a>', 'swarm'],
		['<a href="#" class="bg-icon rounded-icon soc-triplej"></a>', 'triplej'],
		['<a href="#" class="bg-icon rounded-icon soc-yammer"></a>', 'yammer'],
		['<a href="#" class="bg-icon rounded-icon soc-stackoverflow"></a>', 'stackoverflow'],
		['<a href="#" class="bg-icon rounded-icon soc-drupal"></a>', 'drupal'],
		['<a href="#" class="bg-icon rounded-icon soc-odnoklassniki"></a>', 'odnoklassniki'],
		['<a href="#" class="bg-icon rounded-icon soc-android"></a>', 'android'],
		['<a href="#" class="bg-icon rounded-icon soc-meetup"></a>', 'meetup'],
		['<a href="#" class="bg-icon rounded-icon soc-persona"></a>', 'persona'],
		['<a href="#" class="bg-icon rounded-icon soc-amazon"></a>', 'amazon'],
		['<a href="#" class="bg-icon rounded-icon soc-ello"></a>', 'ello'],
		['<a href="#" class="bg-icon rounded-icon soc-mixcloud"></a>', 'mixcloud'],
		['<a href="#" class="bg-icon rounded-icon soc-8tracks"></a>', '8tracks'],
		['<a href="#" class="bg-icon rounded-icon soc-twitch"></a>', 'twitch'],
		['<a href="#" class="bg-icon rounded-icon soc-airbnb"></a>', 'airbnb'],
		['<a href="#" class="bg-icon rounded-icon soc-pocket"></a>', 'pocket'],
		['<a href="#" class="color-icon bg-icon soc-twitter"></a>', 'twitter'],
		['<a href="#" class="color-icon bg-icon soc-facebook"></a>', 'facebook'],
		['<a href="#" class="color-icon bg-icon soc-google"></a>', 'google'],
		['<a href="#" class="color-icon bg-icon soc-pinterest"></a>', 'pinterest'],
		['<a href="#" class="color-icon bg-icon soc-foursquare"></a>', 'foursquare'],
		['<a href="#" class="color-icon bg-icon soc-yahoo"></a>', 'yahoo'],
		['<a href="#" class="color-icon bg-icon soc-skype"></a>', 'skype'],
		['<a href="#" class="color-icon bg-icon soc-yelp"></a>', 'yelp'],
		['<a href="#" class="color-icon bg-icon soc-feedburner"></a>', 'feedburner'],
		['<a href="#" class="color-icon bg-icon soc-linkedin"></a>', 'linkedin'],
		['<a href="#" class="color-icon bg-icon soc-viadeo"></a>', 'viadeo'],
		['<a href="#" class="color-icon bg-icon soc-xing"></a>', 'xing'],
		['<a href="#" class="color-icon bg-icon soc-myspace"></a>', 'myspace'],
		['<a href="#" class="color-icon bg-icon soc-soundcloud"></a>', 'soundcloud'],
		['<a href="#" class="color-icon bg-icon soc-spotify"></a>', 'spotify'],
		['<a href="#" class="color-icon bg-icon soc-grooveshark"></a>', 'grooveshark'],
		['<a href="#" class="color-icon bg-icon soc-lastfm"></a>', 'lastfm'],
		['<a href="#" class="color-icon bg-icon soc-youtube"></a>', 'youtube'],
		['<a href="#" class="color-icon bg-icon soc-vimeo"></a>', 'vimeo'],
		['<a href="#" class="color-icon bg-icon soc-dailymotion"></a>', 'dailymotion'],
		['<a href="#" class="color-icon bg-icon soc-vine"></a>', 'vine'],
		['<a href="#" class="color-icon bg-icon soc-flickr"></a>', 'flickr'],
		['<a href="#" class="color-icon bg-icon soc-500px"></a>', '500px'],
		['<a href="#" class="color-icon bg-icon soc-instagram"></a>', 'instagram'],
		['<a href="#" class="color-icon bg-icon soc-wordpress"></a>', 'wordpress'],
		['<a href="#" class="color-icon bg-icon soc-tumblr"></a>', 'tumblr'],
		['<a href="#" class="color-icon bg-icon soc-blogger"></a>', 'blogger'],
		['<a href="#" class="color-icon bg-icon soc-technorati"></a>', 'technorati'],
		['<a href="#" class="color-icon bg-icon soc-reddit"></a>', 'reddit'],
		['<a href="#" class="color-icon bg-icon soc-dribbble"></a>', 'dribbble'],
		['<a href="#" class="color-icon bg-icon soc-stumbleupon"></a>', 'stumbleupon'],
		['<a href="#" class="color-icon bg-icon soc-digg"></a>', 'digg'],
		['<a href="#" class="color-icon bg-icon soc-envato"></a>', 'envato'],
		['<a href="#" class="color-icon bg-icon soc-behance"></a>', 'behance'],
		['<a href="#" class="color-icon bg-icon soc-delicious"></a>', 'delicious'],
		['<a href="#" class="color-icon bg-icon soc-deviantart"></a>', 'deviantart'],
		['<a href="#" class="color-icon bg-icon soc-forrst"></a>', 'forrst'],
		['<a href="#" class="color-icon bg-icon soc-play"></a>', 'play'],
		['<a href="#" class="color-icon bg-icon soc-zerply"></a>', 'zerply'],
		['<a href="#" class="color-icon bg-icon soc-wikipedia"></a>', 'wikipedia'],
		['<a href="#" class="color-icon bg-icon soc-apple"></a>', 'apple'],
		['<a href="#" class="color-icon bg-icon soc-flattr"></a>', 'flattr'],
		['<a href="#" class="color-icon bg-icon soc-github"></a>', 'github'],
		['<a href="#" class="color-icon bg-icon soc-chimein"></a>', 'chimein'],
		['<a href="#" class="color-icon bg-icon soc-friendfeed"></a>', 'friendfeed'],
		['<a href="#" class="color-icon bg-icon soc-newsvine"></a>', 'newsvine'],
		['<a href="#" class="color-icon bg-icon soc-identica"></a>', 'identica'],
		['<a href="#" class="color-icon bg-icon soc-bebo"></a>', 'bebo'],
		['<a href="#" class="color-icon bg-icon soc-zynga"></a>', 'zynga'],
		['<a href="#" class="color-icon bg-icon soc-steam"></a>', 'steam'],
		['<a href="#" class="color-icon bg-icon soc-xbox"></a>', 'xbox'],
		['<a href="#" class="color-icon bg-icon soc-windows"></a>', 'windows'],
		['<a href="#" class="color-icon bg-icon soc-outlook"></a>', 'outlook'],
		['<a href="#" class="color-icon bg-icon soc-coderwall"></a>', 'coderwall'],
		['<a href="#" class="color-icon bg-icon soc-tripadvisor"></a>', 'tripadvisor'],
		['<a href="#" class="color-icon bg-icon soc-appnet"></a>', 'appnet'],
		['<a href="#" class="color-icon bg-icon soc-goodreads"></a>', 'goodreads'],
		['<a href="#" class="color-icon bg-icon soc-tripit"></a>', 'tripit'],
		['<a href="#" class="color-icon bg-icon soc-lanyrd"></a>', 'lanyrd'],
		['<a href="#" class="color-icon bg-icon soc-slideshare"></a>', 'slideshare'],
		['<a href="#" class="color-icon bg-icon soc-buffer"></a>', 'buffer'],
		['<a href="#" class="color-icon bg-icon soc-rss"></a>', 'rss'],
		['<a href="#" class="color-icon bg-icon soc-vkontakte"></a>', 'vkontakte'],
		['<a href="#" class="color-icon bg-icon soc-disqus"></a>', 'disqus'],
		['<a href="#" class="color-icon bg-icon soc-houzz"></a>', 'houzz'],
		['<a href="#" class="color-icon bg-icon soc-mail"></a>', 'mail'],
		['<a href="#" class="color-icon bg-icon soc-patreon"></a>', 'patreon'],
		['<a href="#" class="color-icon bg-icon soc-paypal"></a>', 'paypal'],
		['<a href="#" class="color-icon bg-icon soc-playstation"></a>', 'playstation'],
		['<a href="#" class="color-icon bg-icon soc-smugmug"></a>', 'smugmug'],
		['<a href="#" class="color-icon bg-icon soc-swarm"></a>', 'swarm'],
		['<a href="#" class="color-icon bg-icon soc-triplej"></a>', 'triplej'],
		['<a href="#" class="color-icon bg-icon soc-yammer"></a>', 'yammer'],
		['<a href="#" class="color-icon bg-icon soc-stackoverflow"></a>', 'stackoverflow'],
		['<a href="#" class="color-icon bg-icon soc-drupal"></a>', 'drupal'],
		['<a href="#" class="color-icon bg-icon soc-odnoklassniki"></a>', 'odnoklassniki'],
		['<a href="#" class="color-icon bg-icon soc-android"></a>', 'android'],
		['<a href="#" class="color-icon bg-icon soc-meetup"></a>', 'meetup'],
		['<a href="#" class="color-icon bg-icon soc-persona"></a>', 'persona'],
		['<a href="#" class="color-icon bg-icon soc-amazon"></a>', 'amazon'],
		['<a href="#" class="color-icon bg-icon soc-ello"></a>', 'ello'],
		['<a href="#" class="color-icon bg-icon soc-mixcloud"></a>', 'mixcloud'],
		['<a href="#" class="color-icon bg-icon soc-8tracks"></a>', '8tracks'],
		['<a href="#" class="color-icon bg-icon soc-twitch"></a>', 'twitch'],
		['<a href="#" class="color-icon bg-icon soc-airbnb"></a>', 'airbnb'],
		['<a href="#" class="color-icon bg-icon soc-pocket"></a>', 'pocket'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-twitter"></a>', 'twitter'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-facebook"></a>', 'facebook'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-google"></a>', 'google'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-pinterest"></a>', 'pinterest'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-foursquare"></a>', 'foursquare'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-yahoo"></a>', 'yahoo'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-skype"></a>', 'skype'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-yelp"></a>', 'yelp'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-feedburner"></a>', 'feedburner'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-linkedin"></a>', 'linkedin'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-viadeo"></a>', 'viadeo'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-xing"></a>', 'xing'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-myspace"></a>', 'myspace'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-soundcloud"></a>', 'soundcloud'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-spotify"></a>', 'spotify'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-grooveshark"></a>', 'grooveshark'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-lastfm"></a>', 'lastfm'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-youtube"></a>', 'youtube'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-vimeo"></a>', 'vimeo'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-dailymotion"></a>', 'dailymotion'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-vine"></a>', 'vine'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-flickr"></a>', 'flickr'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-500px"></a>', '500px'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-instagram"></a>', 'instagram'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-wordpress"></a>', 'wordpress'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-tumblr"></a>', 'tumblr'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-blogger"></a>', 'blogger'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-technorati"></a>', 'technorati'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-reddit"></a>', 'reddit'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-dribbble"></a>', 'dribbble'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-stumbleupon"></a>', 'stumbleupon'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-digg"></a>', 'digg'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-envato"></a>', 'envato'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-behance"></a>', 'behance'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-delicious"></a>', 'delicious'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-deviantart"></a>', 'deviantart'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-forrst"></a>', 'forrst'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-play"></a>', 'play'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-zerply"></a>', 'zerply'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-wikipedia"></a>', 'wikipedia'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-apple"></a>', 'apple'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-flattr"></a>', 'flattr'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-github"></a>', 'github'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-chimein"></a>', 'chimein'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-friendfeed"></a>', 'friendfeed'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-newsvine"></a>', 'newsvine'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-identica"></a>', 'identica'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-bebo"></a>', 'bebo'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-zynga"></a>', 'zynga'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-steam"></a>', 'steam'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-xbox"></a>', 'xbox'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-windows"></a>', 'windows'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-outlook"></a>', 'outlook'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-coderwall"></a>', 'coderwall'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-tripadvisor"></a>', 'tripadvisor'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-appnet"></a>', 'appnet'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-goodreads"></a>', 'goodreads'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-tripit"></a>', 'tripit'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-lanyrd"></a>', 'lanyrd'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-slideshare"></a>', 'slideshare'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-buffer"></a>', 'buffer'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-rss"></a>', 'rss'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-vkontakte"></a>', 'vkontakte'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-disqus"></a>', 'disqus'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-houzz"></a>', 'houzz'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-mail"></a>', 'mail'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-patreon"></a>', 'patreon'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-paypal"></a>', 'paypal'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-playstation"></a>', 'playstation'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-smugmug"></a>', 'smugmug'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-swarm"></a>', 'swarm'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-triplej"></a>', 'triplej'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-yammer"></a>', 'yammer'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-stackoverflow"></a>', 'stackoverflow'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-drupal"></a>', 'drupal'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-odnoklassniki"></a>', 'odnoklassniki'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-android"></a>', 'android'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-meetup"></a>', 'meetup'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-persona"></a>', 'persona'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-amazon"></a>', 'amazon'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-ello"></a>', 'ello'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-mixcloud"></a>', 'mixcloud'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-8tracks"></a>', '8tracks'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-twitch"></a>', 'twitch'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-airbnb"></a>', 'airbnb'],
		['<a href="#" class="color-icon bg-icon rounded-icon soc-pocket"></a>', 'pocket'],
		['<a href="#" class="color-icon soc-twitter"></a>', 'twitter'],
		['<a href="#" class="color-icon soc-facebook"></a>', 'facebook'],
		['<a href="#" class="color-icon soc-google"></a>', 'google'],
		['<a href="#" class="color-icon soc-pinterest"></a>', 'pinterest'],
		['<a href="#" class="color-icon soc-foursquare"></a>', 'foursquare'],
		['<a href="#" class="color-icon soc-yahoo"></a>', 'yahoo'],
		['<a href="#" class="color-icon soc-skype"></a>', 'skype'],
		['<a href="#" class="color-icon soc-yelp"></a>', 'yelp'],
		['<a href="#" class="color-icon soc-feedburner"></a>', 'feedburner'],
		['<a href="#" class="color-icon soc-linkedin"></a>', 'linkedin'],
		['<a href="#" class="color-icon soc-viadeo"></a>', 'viadeo'],
		['<a href="#" class="color-icon soc-xing"></a>', 'xing'],
		['<a href="#" class="color-icon soc-myspace"></a>', 'myspace'],
		['<a href="#" class="color-icon soc-soundcloud"></a>', 'soundcloud'],
		['<a href="#" class="color-icon soc-spotify"></a>', 'spotify'],
		['<a href="#" class="color-icon soc-grooveshark"></a>', 'grooveshark'],
		['<a href="#" class="color-icon soc-lastfm"></a>', 'lastfm'],
		['<a href="#" class="color-icon soc-youtube"></a>', 'youtube'],
		['<a href="#" class="color-icon soc-vimeo"></a>', 'vimeo'],
		['<a href="#" class="color-icon soc-dailymotion"></a>', 'dailymotion'],
		['<a href="#" class="color-icon soc-vine"></a>', 'vine'],
		['<a href="#" class="color-icon soc-flickr"></a>', 'flickr'],
		['<a href="#" class="color-icon soc-500px"></a>', '500px'],
		['<a href="#" class="color-icon soc-instagram"></a>', 'instagram'],
		['<a href="#" class="color-icon soc-wordpress"></a>', 'wordpress'],
		['<a href="#" class="color-icon soc-tumblr"></a>', 'tumblr'],
		['<a href="#" class="color-icon soc-blogger"></a>', 'blogger'],
		['<a href="#" class="color-icon soc-technorati"></a>', 'technorati'],
		['<a href="#" class="color-icon soc-reddit"></a>', 'reddit'],
		['<a href="#" class="color-icon soc-dribbble"></a>', 'dribbble'],
		['<a href="#" class="color-icon soc-stumbleupon"></a>', 'stumbleupon'],
		['<a href="#" class="color-icon soc-digg"></a>', 'digg'],
		['<a href="#" class="color-icon soc-envato"></a>', 'envato'],
		['<a href="#" class="color-icon soc-behance"></a>', 'behance'],
		['<a href="#" class="color-icon soc-delicious"></a>', 'delicious'],
		['<a href="#" class="color-icon soc-deviantart"></a>', 'deviantart'],
		['<a href="#" class="color-icon soc-forrst"></a>', 'forrst'],
		['<a href="#" class="color-icon soc-play"></a>', 'play'],
		['<a href="#" class="color-icon soc-zerply"></a>', 'zerply'],
		['<a href="#" class="color-icon soc-wikipedia"></a>', 'wikipedia'],
		['<a href="#" class="color-icon soc-apple"></a>', 'apple'],
		['<a href="#" class="color-icon soc-flattr"></a>', 'flattr'],
		['<a href="#" class="color-icon soc-github"></a>', 'github'],
		['<a href="#" class="color-icon soc-chimein"></a>', 'chimein'],
		['<a href="#" class="color-icon soc-friendfeed"></a>', 'friendfeed'],
		['<a href="#" class="color-icon soc-newsvine"></a>', 'newsvine'],
		['<a href="#" class="color-icon soc-identica"></a>', 'identica'],
		['<a href="#" class="color-icon soc-bebo"></a>', 'bebo'],
		['<a href="#" class="color-icon soc-zynga"></a>', 'zynga'],
		['<a href="#" class="color-icon soc-steam"></a>', 'steam'],
		['<a href="#" class="color-icon soc-xbox"></a>', 'xbox'],
		['<a href="#" class="color-icon soc-windows"></a>', 'windows'],
		['<a href="#" class="color-icon soc-outlook"></a>', 'outlook'],
		['<a href="#" class="color-icon soc-coderwall"></a>', 'coderwall'],
		['<a href="#" class="color-icon soc-tripadvisor"></a>', 'tripadvisor'],
		['<a href="#" class="color-icon soc-appnet"></a>', 'appnet'],
		['<a href="#" class="color-icon soc-goodreads"></a>', 'goodreads'],
		['<a href="#" class="color-icon soc-tripit"></a>', 'tripit'],
		['<a href="#" class="color-icon soc-lanyrd"></a>', 'lanyrd'],
		['<a href="#" class="color-icon soc-slideshare"></a>', 'slideshare'],
		['<a href="#" class="color-icon soc-buffer"></a>', 'buffer'],
		['<a href="#" class="color-icon soc-rss"></a>', 'rss'],
		['<a href="#" class="color-icon soc-vkontakte"></a>', 'vkontakte'],
		['<a href="#" class="color-icon soc-disqus"></a>', 'disqus'],
		['<a href="#" class="color-icon soc-houzz"></a>', 'houzz'],
		['<a href="#" class="color-icon soc-mail"></a>', 'mail'],
		['<a href="#" class="color-icon soc-patreon"></a>', 'patreon'],
		['<a href="#" class="color-icon soc-paypal"></a>', 'paypal'],
		['<a href="#" class="color-icon soc-playstation"></a>', 'playstation'],
		['<a href="#" class="color-icon soc-smugmug"></a>', 'smugmug'],
		['<a href="#" class="color-icon soc-swarm"></a>', 'swarm'],
		['<a href="#" class="color-icon soc-triplej"></a>', 'triplej'],
		['<a href="#" class="color-icon soc-yammer"></a>', 'yammer'],
		['<a href="#" class="color-icon soc-stackoverflow"></a>', 'stackoverflow'],
		['<a href="#" class="color-icon soc-drupal"></a>', 'drupal'],
		['<a href="#" class="color-icon soc-odnoklassniki"></a>', 'odnoklassniki'],
		['<a href="#" class="color-icon soc-android"></a>', 'android'],
		['<a href="#" class="color-icon soc-meetup"></a>', 'meetup'],
		['<a href="#" class="color-icon soc-persona"></a>', 'persona'],
		['<a href="#" class="color-icon soc-amazon"></a>', 'amazon'],
		['<a href="#" class="color-icon soc-ello"></a>', 'ello'],
		['<a href="#" class="color-icon soc-mixcloud"></a>', 'mixcloud'],
		['<a href="#" class="color-icon soc-8tracks"></a>', '8tracks'],
		['<a href="#" class="color-icon soc-twitch"></a>', 'twitch'],
		['<a href="#" class="color-icon soc-airbnb"></a>', 'airbnb'],
		['<a href="#" class="color-icon soc-pocket"></a>', 'pocket'],
		['<a href="#" class="color-icon border-icon soc-twitter"></a>', 'twitter'],
		['<a href="#" class="color-icon border-icon soc-facebook"></a>', 'facebook'],
		['<a href="#" class="color-icon border-icon soc-google"></a>', 'google'],
		['<a href="#" class="color-icon border-icon soc-pinterest"></a>', 'pinterest'],
		['<a href="#" class="color-icon border-icon soc-foursquare"></a>', 'foursquare'],
		['<a href="#" class="color-icon border-icon soc-yahoo"></a>', 'yahoo'],
		['<a href="#" class="color-icon border-icon soc-skype"></a>', 'skype'],
		['<a href="#" class="color-icon border-icon soc-yelp"></a>', 'yelp'],
		['<a href="#" class="color-icon border-icon soc-feedburner"></a>', 'feedburner'],
		['<a href="#" class="color-icon border-icon soc-linkedin"></a>', 'linkedin'],
		['<a href="#" class="color-icon border-icon soc-viadeo"></a>', 'viadeo'],
		['<a href="#" class="color-icon border-icon soc-xing"></a>', 'xing'],
		['<a href="#" class="color-icon border-icon soc-myspace"></a>', 'myspace'],
		['<a href="#" class="color-icon border-icon soc-soundcloud"></a>', 'soundcloud'],
		['<a href="#" class="color-icon border-icon soc-spotify"></a>', 'spotify'],
		['<a href="#" class="color-icon border-icon soc-grooveshark"></a>', 'grooveshark'],
		['<a href="#" class="color-icon border-icon soc-lastfm"></a>', 'lastfm'],
		['<a href="#" class="color-icon border-icon soc-youtube"></a>', 'youtube'],
		['<a href="#" class="color-icon border-icon soc-vimeo"></a>', 'vimeo'],
		['<a href="#" class="color-icon border-icon soc-dailymotion"></a>', 'dailymotion'],
		['<a href="#" class="color-icon border-icon soc-vine"></a>', 'vine'],
		['<a href="#" class="color-icon border-icon soc-flickr"></a>', 'flickr'],
		['<a href="#" class="color-icon border-icon soc-500px"></a>', '500px'],
		['<a href="#" class="color-icon border-icon soc-instagram"></a>', 'instagram'],
		['<a href="#" class="color-icon border-icon soc-wordpress"></a>', 'wordpress'],
		['<a href="#" class="color-icon border-icon soc-tumblr"></a>', 'tumblr'],
		['<a href="#" class="color-icon border-icon soc-blogger"></a>', 'blogger'],
		['<a href="#" class="color-icon border-icon soc-technorati"></a>', 'technorati'],
		['<a href="#" class="color-icon border-icon soc-reddit"></a>', 'reddit'],
		['<a href="#" class="color-icon border-icon soc-dribbble"></a>', 'dribbble'],
		['<a href="#" class="color-icon border-icon soc-stumbleupon"></a>', 'stumbleupon'],
		['<a href="#" class="color-icon border-icon soc-digg"></a>', 'digg'],
		['<a href="#" class="color-icon border-icon soc-envato"></a>', 'envato'],
		['<a href="#" class="color-icon border-icon soc-behance"></a>', 'behance'],
		['<a href="#" class="color-icon border-icon soc-delicious"></a>', 'delicious'],
		['<a href="#" class="color-icon border-icon soc-deviantart"></a>', 'deviantart'],
		['<a href="#" class="color-icon border-icon soc-forrst"></a>', 'forrst'],
		['<a href="#" class="color-icon border-icon soc-play"></a>', 'play'],
		['<a href="#" class="color-icon border-icon soc-zerply"></a>', 'zerply'],
		['<a href="#" class="color-icon border-icon soc-wikipedia"></a>', 'wikipedia'],
		['<a href="#" class="color-icon border-icon soc-apple"></a>', 'apple'],
		['<a href="#" class="color-icon border-icon soc-flattr"></a>', 'flattr'],
		['<a href="#" class="color-icon border-icon soc-github"></a>', 'github'],
		['<a href="#" class="color-icon border-icon soc-chimein"></a>', 'chimein'],
		['<a href="#" class="color-icon border-icon soc-friendfeed"></a>', 'friendfeed'],
		['<a href="#" class="color-icon border-icon soc-newsvine"></a>', 'newsvine'],
		['<a href="#" class="color-icon border-icon soc-identica"></a>', 'identica'],
		['<a href="#" class="color-icon border-icon soc-bebo"></a>', 'bebo'],
		['<a href="#" class="color-icon border-icon soc-zynga"></a>', 'zynga'],
		['<a href="#" class="color-icon border-icon soc-steam"></a>', 'steam'],
		['<a href="#" class="color-icon border-icon soc-xbox"></a>', 'xbox'],
		['<a href="#" class="color-icon border-icon soc-windows"></a>', 'windows'],
		['<a href="#" class="color-icon border-icon soc-outlook"></a>', 'outlook'],
		['<a href="#" class="color-icon border-icon soc-coderwall"></a>', 'coderwall'],
		['<a href="#" class="color-icon border-icon soc-tripadvisor"></a>', 'tripadvisor'],
		['<a href="#" class="color-icon border-icon soc-appnet"></a>', 'appnet'],
		['<a href="#" class="color-icon border-icon soc-goodreads"></a>', 'goodreads'],
		['<a href="#" class="color-icon border-icon soc-tripit"></a>', 'tripit'],
		['<a href="#" class="color-icon border-icon soc-lanyrd"></a>', 'lanyrd'],
		['<a href="#" class="color-icon border-icon soc-slideshare"></a>', 'slideshare'],
		['<a href="#" class="color-icon border-icon soc-buffer"></a>', 'buffer'],
		['<a href="#" class="color-icon border-icon soc-rss"></a>', 'rss'],
		['<a href="#" class="color-icon border-icon soc-vkontakte"></a>', 'vkontakte'],
		['<a href="#" class="color-icon border-icon soc-disqus"></a>', 'disqus'],
		['<a href="#" class="color-icon border-icon soc-houzz"></a>', 'houzz'],
		['<a href="#" class="color-icon border-icon soc-mail"></a>', 'mail'],
		['<a href="#" class="color-icon border-icon soc-patreon"></a>', 'patreon'],
		['<a href="#" class="color-icon border-icon soc-paypal"></a>', 'paypal'],
		['<a href="#" class="color-icon border-icon soc-playstation"></a>', 'playstation'],
		['<a href="#" class="color-icon border-icon soc-smugmug"></a>', 'smugmug'],
		['<a href="#" class="color-icon border-icon soc-swarm"></a>', 'swarm'],
		['<a href="#" class="color-icon border-icon soc-triplej"></a>', 'triplej'],
		['<a href="#" class="color-icon border-icon soc-yammer"></a>', 'yammer'],
		['<a href="#" class="color-icon border-icon soc-stackoverflow"></a>', 'stackoverflow'],
		['<a href="#" class="color-icon border-icon soc-drupal"></a>', 'drupal'],
		['<a href="#" class="color-icon border-icon soc-odnoklassniki"></a>', 'odnoklassniki'],
		['<a href="#" class="color-icon border-icon soc-android"></a>', 'android'],
		['<a href="#" class="color-icon border-icon soc-meetup"></a>', 'meetup'],
		['<a href="#" class="color-icon border-icon soc-persona"></a>', 'persona'],
		['<a href="#" class="color-icon border-icon soc-amazon"></a>', 'amazon'],
		['<a href="#" class="color-icon border-icon soc-ello"></a>', 'ello'],
		['<a href="#" class="color-icon border-icon soc-mixcloud"></a>', 'mixcloud'],
		['<a href="#" class="color-icon border-icon soc-8tracks"></a>', '8tracks'],
		['<a href="#" class="color-icon border-icon soc-twitch"></a>', 'twitch'],
		['<a href="#" class="color-icon border-icon soc-airbnb"></a>', 'airbnb'],
		['<a href="#" class="color-icon border-icon soc-pocket"></a>', 'pocket'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-twitter"></a>', 'twitter'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-facebook"></a>', 'facebook'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-google"></a>', 'google'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-pinterest"></a>', 'pinterest'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-foursquare"></a>', 'foursquare'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-yahoo"></a>', 'yahoo'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-skype"></a>', 'skype'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-yelp"></a>', 'yelp'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-feedburner"></a>', 'feedburner'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-linkedin"></a>', 'linkedin'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-viadeo"></a>', 'viadeo'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-xing"></a>', 'xing'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-myspace"></a>', 'myspace'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-soundcloud"></a>', 'soundcloud'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-spotify"></a>', 'spotify'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-grooveshark"></a>', 'grooveshark'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-lastfm"></a>', 'lastfm'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-youtube"></a>', 'youtube'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-vimeo"></a>', 'vimeo'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-dailymotion"></a>', 'dailymotion'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-vine"></a>', 'vine'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-flickr"></a>', 'flickr'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-500px"></a>', '500px'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-instagram"></a>', 'instagram'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-wordpress"></a>', 'wordpress'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-tumblr"></a>', 'tumblr'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-blogger"></a>', 'blogger'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-technorati"></a>', 'technorati'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-reddit"></a>', 'reddit'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-dribbble"></a>', 'dribbble'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-stumbleupon"></a>', 'stumbleupon'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-digg"></a>', 'digg'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-envato"></a>', 'envato'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-behance"></a>', 'behance'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-delicious"></a>', 'delicious'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-deviantart"></a>', 'deviantart'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-forrst"></a>', 'forrst'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-play"></a>', 'play'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-zerply"></a>', 'zerply'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-wikipedia"></a>', 'wikipedia'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-apple"></a>', 'apple'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-flattr"></a>', 'flattr'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-github"></a>', 'github'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-chimein"></a>', 'chimein'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-friendfeed"></a>', 'friendfeed'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-newsvine"></a>', 'newsvine'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-identica"></a>', 'identica'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-bebo"></a>', 'bebo'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-zynga"></a>', 'zynga'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-steam"></a>', 'steam'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-xbox"></a>', 'xbox'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-windows"></a>', 'windows'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-outlook"></a>', 'outlook'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-coderwall"></a>', 'coderwall'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-tripadvisor"></a>', 'tripadvisor'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-appnet"></a>', 'appnet'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-goodreads"></a>', 'goodreads'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-tripit"></a>', 'tripit'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-lanyrd"></a>', 'lanyrd'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-slideshare"></a>', 'slideshare'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-buffer"></a>', 'buffer'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-rss"></a>', 'rss'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-vkontakte"></a>', 'vkontakte'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-disqus"></a>', 'disqus'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-houzz"></a>', 'houzz'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-mail"></a>', 'mail'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-patreon"></a>', 'patreon'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-paypal"></a>', 'paypal'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-playstation"></a>', 'playstation'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-smugmug"></a>', 'smugmug'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-swarm"></a>', 'swarm'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-triplej"></a>', 'triplej'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-yammer"></a>', 'yammer'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-stackoverflow"></a>', 'stackoverflow'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-drupal"></a>', 'drupal'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-odnoklassniki"></a>', 'odnoklassniki'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-android"></a>', 'android'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-meetup"></a>', 'meetup'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-persona"></a>', 'persona'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-amazon"></a>', 'amazon'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-ello"></a>', 'ello'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-mixcloud"></a>', 'mixcloud'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-8tracks"></a>', '8tracks'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-twitch"></a>', 'twitch'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-airbnb"></a>', 'airbnb'],
		['<a href="#" class="color-icon border-icon rounded-icon soc-pocket"></a>', 'pocket'],
		['<a href="#" class="color-bg-icon soc-twitter"></a>', 'twitter'],
		['<a href="#" class="color-bg-icon soc-facebook"></a>', 'facebook'],
		['<a href="#" class="color-bg-icon soc-google"></a>', 'google'],
		['<a href="#" class="color-bg-icon soc-pinterest"></a>', 'pinterest'],
		['<a href="#" class="color-bg-icon soc-foursquare"></a>', 'foursquare'],
		['<a href="#" class="color-bg-icon soc-yahoo"></a>', 'yahoo'],
		['<a href="#" class="color-bg-icon soc-skype"></a>', 'skype'],
		['<a href="#" class="color-bg-icon soc-yelp"></a>', 'yelp'],
		['<a href="#" class="color-bg-icon soc-feedburner"></a>', 'feedburner'],
		['<a href="#" class="color-bg-icon soc-linkedin"></a>', 'linkedin'],
		['<a href="#" class="color-bg-icon soc-viadeo"></a>', 'viadeo'],
		['<a href="#" class="color-bg-icon soc-xing"></a>', 'xing'],
		['<a href="#" class="color-bg-icon soc-myspace"></a>', 'myspace'],
		['<a href="#" class="color-bg-icon soc-soundcloud"></a>', 'soundcloud'],
		['<a href="#" class="color-bg-icon soc-spotify"></a>', 'spotify'],
		['<a href="#" class="color-bg-icon soc-grooveshark"></a>', 'grooveshark'],
		['<a href="#" class="color-bg-icon soc-lastfm"></a>', 'lastfm'],
		['<a href="#" class="color-bg-icon soc-youtube"></a>', 'youtube'],
		['<a href="#" class="color-bg-icon soc-vimeo"></a>', 'vimeo'],
		['<a href="#" class="color-bg-icon soc-dailymotion"></a>', 'dailymotion'],
		['<a href="#" class="color-bg-icon soc-vine"></a>', 'vine'],
		['<a href="#" class="color-bg-icon soc-flickr"></a>', 'flickr'],
		['<a href="#" class="color-bg-icon soc-500px"></a>', '500px'],
		['<a href="#" class="color-bg-icon soc-instagram"></a>', 'instagram'],
		['<a href="#" class="color-bg-icon soc-wordpress"></a>', 'wordpress'],
		['<a href="#" class="color-bg-icon soc-tumblr"></a>', 'tumblr'],
		['<a href="#" class="color-bg-icon soc-blogger"></a>', 'blogger'],
		['<a href="#" class="color-bg-icon soc-technorati"></a>', 'technorati'],
		['<a href="#" class="color-bg-icon soc-reddit"></a>', 'reddit'],
		['<a href="#" class="color-bg-icon soc-dribbble"></a>', 'dribbble'],
		['<a href="#" class="color-bg-icon soc-stumbleupon"></a>', 'stumbleupon'],
		['<a href="#" class="color-bg-icon soc-digg"></a>', 'digg'],
		['<a href="#" class="color-bg-icon soc-envato"></a>', 'envato'],
		['<a href="#" class="color-bg-icon soc-behance"></a>', 'behance'],
		['<a href="#" class="color-bg-icon soc-delicious"></a>', 'delicious'],
		['<a href="#" class="color-bg-icon soc-deviantart"></a>', 'deviantart'],
		['<a href="#" class="color-bg-icon soc-forrst"></a>', 'forrst'],
		['<a href="#" class="color-bg-icon soc-play"></a>', 'play'],
		['<a href="#" class="color-bg-icon soc-zerply"></a>', 'zerply'],
		['<a href="#" class="color-bg-icon soc-wikipedia"></a>', 'wikipedia'],
		['<a href="#" class="color-bg-icon soc-apple"></a>', 'apple'],
		['<a href="#" class="color-bg-icon soc-flattr"></a>', 'flattr'],
		['<a href="#" class="color-bg-icon soc-github"></a>', 'github'],
		['<a href="#" class="color-bg-icon soc-chimein"></a>', 'chimein'],
		['<a href="#" class="color-bg-icon soc-friendfeed"></a>', 'friendfeed'],
		['<a href="#" class="color-bg-icon soc-newsvine"></a>', 'newsvine'],
		['<a href="#" class="color-bg-icon soc-identica"></a>', 'identica'],
		['<a href="#" class="color-bg-icon soc-bebo"></a>', 'bebo'],
		['<a href="#" class="color-bg-icon soc-zynga"></a>', 'zynga'],
		['<a href="#" class="color-bg-icon soc-steam"></a>', 'steam'],
		['<a href="#" class="color-bg-icon soc-xbox"></a>', 'xbox'],
		['<a href="#" class="color-bg-icon soc-windows"></a>', 'windows'],
		['<a href="#" class="color-bg-icon soc-outlook"></a>', 'outlook'],
		['<a href="#" class="color-bg-icon soc-coderwall"></a>', 'coderwall'],
		['<a href="#" class="color-bg-icon soc-tripadvisor"></a>', 'tripadvisor'],
		['<a href="#" class="color-bg-icon soc-appnet"></a>', 'appnet'],
		['<a href="#" class="color-bg-icon soc-goodreads"></a>', 'goodreads'],
		['<a href="#" class="color-bg-icon soc-tripit"></a>', 'tripit'],
		['<a href="#" class="color-bg-icon soc-lanyrd"></a>', 'lanyrd'],
		['<a href="#" class="color-bg-icon soc-slideshare"></a>', 'slideshare'],
		['<a href="#" class="color-bg-icon soc-buffer"></a>', 'buffer'],
		['<a href="#" class="color-bg-icon soc-rss"></a>', 'rss'],
		['<a href="#" class="color-bg-icon soc-vkontakte"></a>', 'vkontakte'],
		['<a href="#" class="color-bg-icon soc-disqus"></a>', 'disqus'],
		['<a href="#" class="color-bg-icon soc-houzz"></a>', 'houzz'],
		['<a href="#" class="color-bg-icon soc-mail"></a>', 'mail'],
		['<a href="#" class="color-bg-icon soc-patreon"></a>', 'patreon'],
		['<a href="#" class="color-bg-icon soc-paypal"></a>', 'paypal'],
		['<a href="#" class="color-bg-icon soc-playstation"></a>', 'playstation'],
		['<a href="#" class="color-bg-icon soc-smugmug"></a>', 'smugmug'],
		['<a href="#" class="color-bg-icon soc-swarm"></a>', 'swarm'],
		['<a href="#" class="color-bg-icon soc-triplej"></a>', 'triplej'],
		['<a href="#" class="color-bg-icon soc-yammer"></a>', 'yammer'],
		['<a href="#" class="color-bg-icon soc-stackoverflow"></a>', 'stackoverflow'],
		['<a href="#" class="color-bg-icon soc-drupal"></a>', 'drupal'],
		['<a href="#" class="color-bg-icon soc-odnoklassniki"></a>', 'odnoklassniki'],
		['<a href="#" class="color-bg-icon soc-android"></a>', 'android'],
		['<a href="#" class="color-bg-icon soc-meetup"></a>', 'meetup'],
		['<a href="#" class="color-bg-icon soc-persona"></a>', 'persona'],
		['<a href="#" class="color-bg-icon soc-amazon"></a>', 'amazon'],
		['<a href="#" class="color-bg-icon soc-ello"></a>', 'ello'],
		['<a href="#" class="color-bg-icon soc-mixcloud"></a>', 'mixcloud'],
		['<a href="#" class="color-bg-icon soc-8tracks"></a>', '8tracks'],
		['<a href="#" class="color-bg-icon soc-twitch"></a>', 'twitch'],
		['<a href="#" class="color-bg-icon soc-airbnb"></a>', 'airbnb'],
		['<a href="#" class="color-bg-icon soc-pocket"></a>', 'pocket'],
		['<a href="#" class="color-bg-icon rounded-icon soc-twitter"></a>', 'twitter'],
		['<a href="#" class="color-bg-icon rounded-icon soc-facebook"></a>', 'facebook'],
		['<a href="#" class="color-bg-icon rounded-icon soc-google"></a>', 'google'],
		['<a href="#" class="color-bg-icon rounded-icon soc-pinterest"></a>', 'pinterest'],
		['<a href="#" class="color-bg-icon rounded-icon soc-foursquare"></a>', 'foursquare'],
		['<a href="#" class="color-bg-icon rounded-icon soc-yahoo"></a>', 'yahoo'],
		['<a href="#" class="color-bg-icon rounded-icon soc-skype"></a>', 'skype'],
		['<a href="#" class="color-bg-icon rounded-icon soc-yelp"></a>', 'yelp'],
		['<a href="#" class="color-bg-icon rounded-icon soc-feedburner"></a>', 'feedburner'],
		['<a href="#" class="color-bg-icon rounded-icon soc-linkedin"></a>', 'linkedin'],
		['<a href="#" class="color-bg-icon rounded-icon soc-viadeo"></a>', 'viadeo'],
		['<a href="#" class="color-bg-icon rounded-icon soc-xing"></a>', 'xing'],
		['<a href="#" class="color-bg-icon rounded-icon soc-myspace"></a>', 'myspace'],
		['<a href="#" class="color-bg-icon rounded-icon soc-soundcloud"></a>', 'soundcloud'],
		['<a href="#" class="color-bg-icon rounded-icon soc-spotify"></a>', 'spotify'],
		['<a href="#" class="color-bg-icon rounded-icon soc-grooveshark"></a>', 'grooveshark'],
		['<a href="#" class="color-bg-icon rounded-icon soc-lastfm"></a>', 'lastfm'],
		['<a href="#" class="color-bg-icon rounded-icon soc-youtube"></a>', 'youtube'],
		['<a href="#" class="color-bg-icon rounded-icon soc-vimeo"></a>', 'vimeo'],
		['<a href="#" class="color-bg-icon rounded-icon soc-dailymotion"></a>', 'dailymotion'],
		['<a href="#" class="color-bg-icon rounded-icon soc-vine"></a>', 'vine'],
		['<a href="#" class="color-bg-icon rounded-icon soc-flickr"></a>', 'flickr'],
		['<a href="#" class="color-bg-icon rounded-icon soc-500px"></a>', '500px'],
		['<a href="#" class="color-bg-icon rounded-icon soc-instagram"></a>', 'instagram'],
		['<a href="#" class="color-bg-icon rounded-icon soc-wordpress"></a>', 'wordpress'],
		['<a href="#" class="color-bg-icon rounded-icon soc-tumblr"></a>', 'tumblr'],
		['<a href="#" class="color-bg-icon rounded-icon soc-blogger"></a>', 'blogger'],
		['<a href="#" class="color-bg-icon rounded-icon soc-technorati"></a>', 'technorati'],
		['<a href="#" class="color-bg-icon rounded-icon soc-reddit"></a>', 'reddit'],
		['<a href="#" class="color-bg-icon rounded-icon soc-dribbble"></a>', 'dribbble'],
		['<a href="#" class="color-bg-icon rounded-icon soc-stumbleupon"></a>', 'stumbleupon'],
		['<a href="#" class="color-bg-icon rounded-icon soc-digg"></a>', 'digg'],
		['<a href="#" class="color-bg-icon rounded-icon soc-envato"></a>', 'envato'],
		['<a href="#" class="color-bg-icon rounded-icon soc-behance"></a>', 'behance'],
		['<a href="#" class="color-bg-icon rounded-icon soc-delicious"></a>', 'delicious'],
		['<a href="#" class="color-bg-icon rounded-icon soc-deviantart"></a>', 'deviantart'],
		['<a href="#" class="color-bg-icon rounded-icon soc-forrst"></a>', 'forrst'],
		['<a href="#" class="color-bg-icon rounded-icon soc-play"></a>', 'play'],
		['<a href="#" class="color-bg-icon rounded-icon soc-zerply"></a>', 'zerply'],
		['<a href="#" class="color-bg-icon rounded-icon soc-wikipedia"></a>', 'wikipedia'],
		['<a href="#" class="color-bg-icon rounded-icon soc-apple"></a>', 'apple'],
		['<a href="#" class="color-bg-icon rounded-icon soc-flattr"></a>', 'flattr'],
		['<a href="#" class="color-bg-icon rounded-icon soc-github"></a>', 'github'],
		['<a href="#" class="color-bg-icon rounded-icon soc-chimein"></a>', 'chimein'],
		['<a href="#" class="color-bg-icon rounded-icon soc-friendfeed"></a>', 'friendfeed'],
		['<a href="#" class="color-bg-icon rounded-icon soc-newsvine"></a>', 'newsvine'],
		['<a href="#" class="color-bg-icon rounded-icon soc-identica"></a>', 'identica'],
		['<a href="#" class="color-bg-icon rounded-icon soc-bebo"></a>', 'bebo'],
		['<a href="#" class="color-bg-icon rounded-icon soc-zynga"></a>', 'zynga'],
		['<a href="#" class="color-bg-icon rounded-icon soc-steam"></a>', 'steam'],
		['<a href="#" class="color-bg-icon rounded-icon soc-xbox"></a>', 'xbox'],
		['<a href="#" class="color-bg-icon rounded-icon soc-windows"></a>', 'windows'],
		['<a href="#" class="color-bg-icon rounded-icon soc-outlook"></a>', 'outlook'],
		['<a href="#" class="color-bg-icon rounded-icon soc-coderwall"></a>', 'coderwall'],
		['<a href="#" class="color-bg-icon rounded-icon soc-tripadvisor"></a>', 'tripadvisor'],
		['<a href="#" class="color-bg-icon rounded-icon soc-appnet"></a>', 'appnet'],
		['<a href="#" class="color-bg-icon rounded-icon soc-goodreads"></a>', 'goodreads'],
		['<a href="#" class="color-bg-icon rounded-icon soc-tripit"></a>', 'tripit'],
		['<a href="#" class="color-bg-icon rounded-icon soc-lanyrd"></a>', 'lanyrd'],
		['<a href="#" class="color-bg-icon rounded-icon soc-slideshare"></a>', 'slideshare'],
		['<a href="#" class="color-bg-icon rounded-icon soc-buffer"></a>', 'buffer'],
		['<a href="#" class="color-bg-icon rounded-icon soc-rss"></a>', 'rss'],
		['<a href="#" class="color-bg-icon rounded-icon soc-vkontakte"></a>', 'vkontakte'],
		['<a href="#" class="color-bg-icon rounded-icon soc-disqus"></a>', 'disqus'],
		['<a href="#" class="color-bg-icon rounded-icon soc-houzz"></a>', 'houzz'],
		['<a href="#" class="color-bg-icon rounded-icon soc-mail"></a>', 'mail'],
		['<a href="#" class="color-bg-icon rounded-icon soc-patreon"></a>', 'patreon'],
		['<a href="#" class="color-bg-icon rounded-icon soc-paypal"></a>', 'paypal'],
		['<a href="#" class="color-bg-icon rounded-icon soc-playstation"></a>', 'playstation'],
		['<a href="#" class="color-bg-icon rounded-icon soc-smugmug"></a>', 'smugmug'],
		['<a href="#" class="color-bg-icon rounded-icon soc-swarm"></a>', 'swarm'],
		['<a href="#" class="color-bg-icon rounded-icon soc-triplej"></a>', 'triplej'],
		['<a href="#" class="color-bg-icon rounded-icon soc-yammer"></a>', 'yammer'],
		['<a href="#" class="color-bg-icon rounded-icon soc-stackoverflow"></a>', 'stackoverflow'],
		['<a href="#" class="color-bg-icon rounded-icon soc-drupal"></a>', 'drupal'],
		['<a href="#" class="color-bg-icon rounded-icon soc-odnoklassniki"></a>', 'odnoklassniki'],
		['<a href="#" class="color-bg-icon rounded-icon soc-android"></a>', 'android'],
		['<a href="#" class="color-bg-icon rounded-icon soc-meetup"></a>', 'meetup'],
		['<a href="#" class="color-bg-icon rounded-icon soc-persona"></a>', 'persona'],
		['<a href="#" class="color-bg-icon rounded-icon soc-amazon"></a>', 'amazon'],
		['<a href="#" class="color-bg-icon rounded-icon soc-ello"></a>', 'ello'],
		['<a href="#" class="color-bg-icon rounded-icon soc-mixcloud"></a>', 'mixcloud'],
		['<a href="#" class="color-bg-icon rounded-icon soc-8tracks"></a>', '8tracks'],
		['<a href="#" class="color-bg-icon rounded-icon soc-twitch"></a>', 'twitch'],
		['<a href="#" class="color-bg-icon rounded-icon soc-airbnb"></a>', 'airbnb'],
		['<a href="#" class="color-bg-icon rounded-icon soc-pocket"></a>', 'pocket'],
	];

	function showDialog() {
		var gridHtml, x, y, win;

		function getParentTd(elm) {
			while (elm) {
				if (elm.nodeName == 'TD') {
					return elm;
				}

				elm = elm.parentNode;
			}
		}

		gridHtml = '<table role="presentation" cellspacing="0" class="mce-icons-social"><tbody>';

		var width = 12;
		var height = Math.ceil(icon.length / width);
		for (y = 0; y < height; y++) {
			gridHtml += '<tr>';

			for (x = 0; x < width; x++) {
				var index = y * width + x;
				if (index < icon.length) {
					var chr = icon[index];

					gridHtml += '<td title="' + chr[1] + '"><div tabindex="-1" title="' + chr[1] + '" role="button">' +
						chr[0] + '</div></td>';
				} else {
					gridHtml += '<td />';
				}
			}

			gridHtml += '</tr>';
		}

		gridHtml += '</tbody></table>';

		var iconPanel = {
			type: 'container',
			html: gridHtml,
			onclick: function(e) {
				e.preventDefault();
				var target = e.target;
				if (/^(A)$/.test(target.nodeName)) {
					if (getParentTd(target).firstChild) {
						editor.execCommand('mceInsertContent', false, tinymce.trim('&nbsp;' + target.outerHTML + '&nbsp;'));

						if (!e.ctrlKey) {
							win.close();
						}
					}
				}
			},
		};

		win = editor.windowManager.open({
			title: "Template Social Icons",
			spacing: 10,
			padding: 10,
			style: 'max-height: 98%; overflow-y: auto; overflow-x: hidden;',
			items: [
				iconPanel,
				{
					type: 'container',
					layout: 'flex',
					direction: 'column',
					align: 'center',
					spacing: 5,
					minWidth: 0,
					minHeight: 0,
					items: [
						{
							type: 'label',
							name: 'preview',
							text: ' ',
							style: 'display:none;',
							border: 0,
							minWidth: 0,
							minHeight: 0
						},
						{
							type: 'label',
							name: 'previewTitle',
							text: ' ',
							style: 'display:none;',
							border: 0,
							minWidth: 0,
							minHeight: 0
						}
					]
				}
			],
			buttons: [
				{text: "Close", onclick: function() {
					win.close();
				}}
			]
		});
	}

	editor.addButton('iconsocial', {
		icon: 'socicon',
		tooltip: 'Template Social Icons',
		onclick: showDialog
	});

	editor.addMenuItem('iconsocial', {
		icon: 'socicon',
		text: 'Template Social Icons',
		onclick: showDialog,
		context: 'insert'
	});
});